ACCOUNT_ID: ${env:ACCOUNT_ID}

appSync:
  name: Currency Converter
  authenticationType: API_KEY
  serviceRole: AppSyncServiceRole
  schema: src/currency/appsync/schema.graphql
  mappingTemplatesLocation: src/currency/appsync/mapping-templates
  mappingTemplates:
    - dataSource: CurrencyConverter
      type: Query
      field: convertCurrency
      request: "convertCurrency-request-mapping-template.txt"
      response: "convertCurrency-response-mapping-template.txt"
    - dataSource: ListCurrencies
      type: Query
      field: listCurrencies
      request: "listCurrencies-request-mapping-template.txt"
      response: "listCurrencies-response-mapping-template.txt"
  additionalAuthenticationProviders:
    - authenticationType: AWS_IAM
  logConfig:
    loggingRoleArn: { Fn::GetAtt: [AppSyncLogRole, Arn] }
    level: ERROR # Logging Level: NONE | ERROR | ALL
    excludeVerboseContent: true
  dataSources:
    - type: AWS_LAMBDA
      name: CurrencyConverter
      description: 'Currency Converter DataSource'
      config:
        functionName: convertCurrency
        serviceRoleArn:  { Fn::GetAtt: [AppSyncServiceRole, Arn] } 
    - type: AWS_LAMBDA
      name: ListCurrencies
      description: 'List Currencies DataSource'
      config:
        functionName: listCurrencies
        serviceRoleArn:  { Fn::GetAtt: [AppSyncServiceRole, Arn] }         