Resources: 
  CurrencyTransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CURRENCY_TRANSACTIONS
      # GlobalSecondaryIndexes: 
      #   - IndexName: leagueId-position-index
      #     KeySchema:
      #       - AttributeName: "leagueId"
      #         KeyType: "HASH"
      #       - AttributeName: "position"
      #         KeyType: "RANGE"
      #     Projection: 
      #       ProjectionType: ALL
      #     ProvisionedThroughput:
      #       ReadCapacityUnits: 10
      #       WriteCapacityUnits: 10
      AttributeDefinitions:
        - AttributeName: "PK"
          AttributeType: "S"
        - AttributeName: "SK"
          AttributeType: "S"
      KeySchema: 
        - AttributeName: "PK"
          KeyType: "HASH"
        - AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5