Resources:
    AppSyncServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "Lambda-AppSyncServiceRole-${self:provider.stage}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Lambda-AppSyncServiceRole-Policy-${self:provider.stage}"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                    - "logs:CreateLogGroup"
                    - "logs:CreateLogStream"
                    - "logs:PutLogEvents"
                  Resource:
                    - "arn:aws:lambda:${self:provider.region}:${self:custom.accountId}:*"
                - 
                  Effect: "Allow"
                  Action:
                    - "dynamodb:DescribeTable"
                    - "dynamodb:GetItem"
                    - "dynamodb:PutItem"
                    - "dynamodb:Query"
                  Resource:
                    - "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:*"

    AppSyncLogRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "Lambda-AppSyncLogRole-${self:provider.stage}"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          -
            PolicyName: "Lambda-AppSyncLogRole-Policy-${self:provider.stage}"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                -
                  Effect: "Allow"
                  Action:
                    - "logs:*"
                  Resource:
                    - "arn:aws:logs:${self:provider.region}:${self:custom.accountId}:*"